parameters:
    api_routes:
        general_account_types: /general/account-types
        general_file_types: /general/file-types
        general_media_types: /general/media-types
        users: /users
        account: /account
        account_password: /account/password
        account_email: /account/email
        account_type: /account/type
        account_token: /account/token
        file: /data/file
        files: /data/files
        blockchain: /data/blockchain
        blockchain_coins: /data/blockchain/coins
        blockchain_info: /data/blockchain/info
        blockchain_test: /data/blockchain/test