#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

index:
    path: /
    defaults: { _controller: AppBundle:Default:index }

login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

logout:
    path: /logout

register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

edit_profile:
    path: /user/profile
    defaults: { _controller: AppBundle:User:editProfile }

validate_token:
    path: /user/validate
    defaults: { _controller: AppBundle:User:validateToken }