#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

index:
    path: /
    defaults: { _controller: AppBundle:Default:index }

hello:
    path: /hello
    defaults: { _controller: AppBundle:Default:test }