#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

index:
    path: /
    defaults: { _controller: AppBundle:Default:index }

login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

logout:
    path: /logout

register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

password_reset:
    path: /user/password-reset
    defaults: { _controller: AppBundle:User:passwordReset }

user_configuration:
    path: /user/configuration
    defaults: { _controller: AppBundle:User:configuration }

user_identity:
    path: /user/identity
    defaults: { _controller: AppBundle:User:identity }

validate_token:
    path: /user/validate
    defaults: { _controller: AppBundle:User:validateToken }

file_library:
    path: /data/library
    defaults: { _controller: AppBundle:Data:fileLibrary }

file_upload:
    path: /data/upload
    defaults: { _controller: AppBundle:Data:uploadFile }

file_upload_res:
    path: /data/upload/result
    defaults: { _controller: AppBundle:Data:uploadFileResult }

generate_signature_certificate:
    path: /data/signature/generate-certificate
    defaults: { _controller: AppBundle:Data:generateSignCert }

file_signature:
    path: /data/signature/{token}
    defaults: { _controller: AppBundle:Data:getSignableDoc }

file_signature_certificate:
    path: /data/signature/{token}/certificate
    defaults: { _controller: AppBundle:Data:signatureCertificate }

ajax_generate_sign_code:
    path: /ajax/generate-sign-code/{token}
    defaults: { _controller: AppBundle:Data:ajaxGenerateCode }

file_view:
    path: /data/view/{file}
    defaults: { _controller: AppBundle:Data:viewFile }

# Education

edu_notarize:
    path: /edu/isdi/notarize
    defaults: { _controller: AppBundle:Edu:createBulkTransaction }

edu_home:
    path: /edu/isdi
    defaults: { _controller: AppBundle:Edu:home }

edu_verify:
    path: /edu/isdi/verify/{uniqueId}
    defaults: { _controller: AppBundle:Edu:verify }

# Private ajax calls
ajax_file_upload:
    path: /ajax/private/upload-file
    defaults: { _controller: AppBundle:Data:ajaxUploadFile }

ajax_close_account:
    path: /ajax/private/close-account
    defaults: { _controller: AppBundle:User:ajaxCloseAccount }

ajax_change_locale:
    path: /ajax/public/change-locale
    defaults: { _controller: AppBundle:Default:ajaxChangeLocale }