#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

index:
    path: /
    defaults: { _controller: AppBundle:Default:index }

login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

logout:
    path: /logout

register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

edit_profile:
    path: /user/profile
    defaults: { _controller: AppBundle:User:editProfile }

validate_token:
    path: /user/validate
    defaults: { _controller: AppBundle:User:validateToken }

file_library:
    path: /data/library
    defaults: { _controller: AppBundle:Data:fileLibrary }

file_upload:
    path: /data/upload
    defaults: { _controller: AppBundle:Data:uploadFile }

file_upload_res:
    path: /data/upload/result
    defaults: { _controller: AppBundle:Data:uploadFileResult }

# Private ajax calls
ajax_file_upload:
    path: /ajax/private/upload-file
    defaults: { _controller: AppBundle:Data:ajaxUploadFile }