imports:
    - { resource: api_routes.yml }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    api_url: ivelasco.api.bindeo.com
    api_token: 75be9f5e5234406d544d84e32e1747e4

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.api_connection:
        class:        AppBundle\Model\ApiConnection
        arguments:    ['%api_url%', '%api_token%', '%api_routes%']

    app.user_provider:
        class: AppBundle\Security\UserProvider
        arguments:    ['@app.api_connection']

    app.authenticacion_success:
        class: AppBundle\Security\AuthenticationSuccess
        arguments:    ['@app.api_connection']
