imports:
    - { resource: api_routes.yml }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    api_url: ivelasco.api.bindeo.com
    api_token: 75be9f5e5234406d544d84e32e1747e4

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # To connect against the API
    app.api_connection:
        class:        AppBundle\Model\ApiConnection
        arguments:    ['%api_url%', '%api_token%', '%api_routes%']

    # Master data factory
    app.master_data:
        class:        AppBundle\Model\MasterDataFactory
        arguments:    ['@app.api_connection']

    # Login with the API
    app.user_provider:
        class: AppBundle\Security\UserProvider
        arguments:    ['@app.api_connection']

    # Validate the logged user against the API
    app.authenticacion_success:
        class: AppBundle\Security\AuthenticationSuccess
        arguments:    ['@app.api_connection', '@monolog.logger']

    # Set the session locale in request
    app.locale_listener:
        class: AppBundle\Listener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    # Set the user locale in session
    app.user_locale_listener:
        class: AppBundle\Listener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    # Forms
    app.form.type.uploadfile:
        class: AppBundle\Form\Type\UploadFileType
        arguments: ['@session', '@app.master_data']
        tags:
            - { name: form.type }

    # Models
    app.model.data:
        class: AppBundle\Model\DataModel
        arguments: ['@app.master_data', '@app.api_connection', '@security.token_storage', '@translator', '%files%']
        tags:
            - { name: app.model }